os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="electric-fence/2.2.0"
    - CONAN_USERNAME="lasote"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1 
    - CONAN_USE_DOCKER=1

  matrix:
    - CONAN_GCC_VERSIONS=4.6 
    - CONAN_GCC_VERSIONS=4.8
    - CONAN_GCC_VERSIONS=4.9
    - CONAN_GCC_VERSIONS=5.2
    - CONAN_GCC_VERSIONS=5.3
    - CONAN_GCC_VERSIONS=5.4
    - CONAN_GCC_VERSIONS=6.2
    - CONAN_GCC_VERSIONS=6.3

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
